import { z } from "zod";
import {
  ActionSchema,
  KnowledgeStatusSchema,
  ModeSchema,
  PortalRoutes,
  type AssistantAction,
  type Mode,
} from "@medy/shared";

export const KnowledgeEntrySchema = z.object({
  id: z.string().min(1),
  domain: ModeSchema,
  category: z.string().min(1),
  intent: z.string().min(1),
  title: z.string().min(1),
  keywords: z.array(z.string()).min(1),
  synonyms: z.record(z.array(z.string())).default({}),
  exampleQuestions: z.array(z.string()).min(1),
  responseSummary: z.string().min(1),
  orderedSteps: z.array(z.string()).default([]),
  warnings: z.array(z.string()).default([]),
  disclaimers: z.array(z.string()).default([]),
  requiredFields: z.array(z.string()).default([]),
  optionalFields: z.array(z.string()).default([]),
  suggestedReplies: z.array(z.string()).default([]),
  availableActions: z.array(ActionSchema).default([]),
  sourceLabel: z.string().min(1),
  sourceStatus: KnowledgeStatusSchema,
  escalationDepartment: z.string().nullable().default(null),
  emergencyFlag: z.boolean().default(false),
  relatedIntents: z.array(z.string()).default([]),
  negativeKeywords: z.array(z.string()).default([]),
});
export type KnowledgeEntry = z.infer<typeof KnowledgeEntrySchema>;

const action = (
  id: string,
  type: AssistantAction["type"],
  label: string,
  target?: string,
  requiresConfirmation = false,
): AssistantAction => ({ id, type, label, target, requiresConfirmation });

type EntryInput = Omit<
  KnowledgeEntry,
  | "synonyms"
  | "orderedSteps"
  | "warnings"
  | "disclaimers"
  | "requiredFields"
  | "optionalFields"
  | "suggestedReplies"
  | "availableActions"
  | "escalationDepartment"
  | "emergencyFlag"
  | "relatedIntents"
  | "negativeKeywords"
> &
  Partial<KnowledgeEntry>;
const entry = (value: EntryInput) =>
  KnowledgeEntrySchema.parse({
    synonyms: {},
    orderedSteps: [],
    warnings: [],
    disclaimers: [],
    requiredFields: [],
    optionalFields: [],
    suggestedReplies: [],
    availableActions: [],
    escalationDepartment: null,
    emergencyFlag: false,
    relatedIntents: [],
    negativeKeywords: [],
    ...value,
  });

const publicSource = "SecureMedy public demo knowledge";
const employeeSource = "M3dyHub employee demo knowledge";
const publicEntries: KnowledgeEntry[] = [
  entry({
    id: "pub-company",
    domain: "public",
    category: "company overview",
    intent: "company_overview",
    title: "About SecureMedy",
    keywords: ["securemedy", "company", "about", "mission"],
    synonyms: {
      company: ["organization", "business"],
      about: ["background", "overview"],
    },
    exampleQuestions: ["What is SecureMedy?", "Tell me about the company"],
    responseSummary:
      "SecureMedy provides physical security and emergency-management support for organizations, properties, and events.",
    suggestedReplies: ["Explore services", "Contact SecureMedy"],
    sourceLabel: publicSource,
    sourceStatus: "approved",
  }),
  entry({
    id: "pub-services",
    domain: "public",
    category: "services",
    intent: "services",
    title: "Security services",
    keywords: [
      "services",
      "security",
      "guard",
      "patrol",
      "surveillance",
      "access",
      "officer",
    ],
    synonyms: {
      guard: ["officer", "protection"],
      patrol: ["roving patrol", "mobile patrol"],
    },
    exampleQuestions: [
      "What security services do you offer?",
      "Do you provide security guards?",
      "Can you provide healthcare security?",
    ],
    responseSummary:
      "SecureMedy supports command operations, roving patrol, surveillance, risk management, access control, alarm response, armed or unarmed security, and event security. Scope and availability require confirmation.",
    suggestedReplies: [
      "Request a quote",
      "Healthcare security",
      "Event security",
    ],
    availableActions: [
      action("lead", "start_form", "Request Security Services"),
    ],
    sourceLabel: publicSource,
    sourceStatus: "approved",
    relatedIntents: ["quote_request", "service_areas"],
  }),
  entry({
    id: "pub-event-quote",
    domain: "public",
    category: "quote requests",
    intent: "event_security_quote",
    title: "Event-security quote",
    keywords: ["event", "quote", "officers", "coverage", "venue"],
    synonyms: {
      event: ["conference", "festival", "wedding", "concert"],
      quote: ["estimate", "pricing", "cost"],
    },
    exampleQuestions: [
      "I need security for an event",
      "Can I get a quote for event security?",
    ],
    responseSummary:
      "A representative can review event location, date, schedule, attendance, venue type, and requested coverage before confirming a quote.",
    orderedSteps: [
      "Collect the event location",
      "Collect the event date",
      "Collect estimated attendance",
      "Collect the requested coverage",
    ],
    requiredFields: [
      "event location",
      "event date",
      "estimated attendance",
      "requested coverage",
    ],
    suggestedReplies: ["Start request", "Speak to Sales"],
    availableActions: [action("lead", "start_form", "Request a Quote")],
    sourceLabel: publicSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Sales",
  }),
  entry({
    id: "pub-service-area",
    domain: "public",
    category: "service areas",
    intent: "service_areas",
    title: "Service areas",
    keywords: ["area", "location", "state", "serve", "coverage"],
    synonyms: {
      area: ["region", "territory"],
      serve: ["operate", "available"],
    },
    exampleQuestions: [
      "Do you serve my area?",
      "Which states do you operate in?",
    ],
    responseSummary:
      "Service availability depends on location, licensing, staffing, and requested scope. A representative must confirm coverage for a specific address.",
    requiredFields: ["service location"],
    suggestedReplies: ["Enter service location", "Contact Sales"],
    sourceLabel: publicSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Sales",
  }),
  entry({
    id: "pub-client-inquiry",
    domain: "public",
    category: "client inquiries",
    intent: "client_inquiry",
    title: "Prospective client inquiry",
    keywords: ["client", "inquiry", "information", "representative"],
    synonyms: { inquiry: ["question", "enquiry"] },
    exampleQuestions: ["I have a client question", "Can someone contact me?"],
    responseSummary:
      "Medy can route a prospective-client inquiry to the appropriate demonstration contact path.",
    requiredFields: ["name", "organization", "contact method", "inquiry"],
    suggestedReplies: ["Start request", "Speak to Sales"],
    availableActions: [
      action("contact", "start_form", "Contact SecureMedy"),
      action("handoff", "escalate", "Speak with Someone"),
    ],
    sourceLabel: publicSource,
    sourceStatus: "approved",
    escalationDepartment: "Sales",
  }),
  entry({
    id: "pub-careers",
    domain: "public",
    category: "careers",
    intent: "careers",
    title: "Careers",
    keywords: ["career", "job", "employment", "hiring", "apply"],
    synonyms: {
      job: ["position", "opening", "vacancy"],
      apply: ["application", "candidate"],
    },
    exampleQuestions: ["Are you hiring?", "How do I apply for a job?"],
    responseSummary:
      "Candidates can review opportunities and application information on SecureMedy's careers page. Availability and hiring decisions are confirmed only by Recruiting or HR.",
    suggestedReplies: ["Apply now", "Application process", "Contact HR"],
    availableActions: [
      action(
        "careers",
        "open_external",
        "View Careers",
        "https://securemedy.com/careers",
      ),
    ],
    sourceLabel: publicSource,
    sourceStatus: "approved",
    escalationDepartment: "Human Resources",
  }),
  entry({
    id: "pub-application",
    domain: "public",
    category: "application process",
    intent: "application_process",
    title: "Application process",
    keywords: ["application", "apply", "resume", "interview", "status"],
    synonyms: { resume: ["cv"], status: ["update", "progress"] },
    exampleQuestions: [
      "What is the application process?",
      "What is my application status?",
    ],
    responseSummary:
      "Use the official careers channel to submit or review application information. Medy cannot view a real candidate record or promise an interview timeline.",
    warnings: ["Do not send sensitive identity documents through chat."],
    suggestedReplies: ["View careers", "Contact HR"],
    availableActions: [
      action(
        "careers",
        "open_external",
        "Apply Now",
        "https://securemedy.com/careers",
      ),
      action("hr", "contact_department", "Contact HR", "Human Resources"),
    ],
    sourceLabel: publicSource,
    sourceStatus: "approved",
    escalationDepartment: "Human Resources",
  }),
  entry({
    id: "pub-qualifications",
    domain: "public",
    category: "qualifications",
    intent: "job_qualifications",
    title: "General job qualifications",
    keywords: [
      "qualification",
      "requirements",
      "license",
      "experience",
      "eligible",
    ],
    synonyms: { qualification: ["requirement", "credential"] },
    exampleQuestions: [
      "What qualifications do I need?",
      "Do I need a security license?",
    ],
    responseSummary:
      "Qualifications vary by position, jurisdiction, and assignment. Confirm the current posting and official licensing requirements before applying.",
    suggestedReplies: ["View careers", "Contact HR"],
    sourceLabel: publicSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Human Resources",
  }),
  entry({
    id: "pub-contact-sales",
    domain: "public",
    category: "contact routing",
    intent: "contact_sales",
    title: "Contact Sales",
    keywords: ["sales", "quote", "contact", "representative"],
    synonyms: { sales: ["business development", "service team"] },
    exampleQuestions: [
      "Contact Sales",
      "I want to speak with a representative",
    ],
    responseSummary:
      "Medy can collect demonstration inquiry details or route you to Sales for service questions.",
    requiredFields: [
      "name",
      "organization",
      "contact method",
      "request summary",
    ],
    suggestedReplies: ["Start request", "Request a quote"],
    availableActions: [
      action("contact", "start_form", "Contact Sales"),
      action("handoff", "escalate", "Speak to Sales"),
    ],
    sourceLabel: publicSource,
    sourceStatus: "approved",
    escalationDepartment: "Sales",
  }),
  entry({
    id: "pub-contact-hr",
    domain: "public",
    category: "contact routing",
    intent: "contact_hr",
    title: "Contact Human Resources",
    keywords: ["hr", "human resources", "recruiter", "employment"],
    synonyms: { hr: ["people team", "human resources"] },
    exampleQuestions: ["How do I contact HR?", "Contact Human Resources"],
    responseSummary:
      "Employment and candidate questions should be confirmed through SecureMedy Human Resources or the official careers channel.",
    suggestedReplies: ["View careers", "Contact HR"],
    availableActions: [
      action("hr", "contact_department", "Contact HR", "Human Resources"),
    ],
    sourceLabel: publicSource,
    sourceStatus: "approved",
    escalationDepartment: "Human Resources",
  }),
  entry({
    id: "pub-complaint",
    domain: "public",
    category: "complaints",
    intent: "complaint",
    title: "Complaint routing",
    keywords: ["complaint", "concern", "problem", "unhappy", "report"],
    synonyms: {
      complaint: ["grievance", "concern"],
      problem: ["issue", "incident"],
    },
    exampleQuestions: [
      "I want to make a complaint",
      "I have a concern about service",
    ],
    responseSummary:
      "Medy can route a complaint but cannot investigate or determine an outcome. For immediate danger, contact emergency services first.",
    requiredFields: [
      "contact method",
      "location or account",
      "concern summary",
    ],
    warnings: ["Do not include unnecessary sensitive personal information."],
    suggestedReplies: ["Start complaint", "Speak to Operations"],
    availableActions: [action("handoff", "escalate", "Speak to Operations")],
    sourceLabel: publicSource,
    sourceStatus: "approved",
    escalationDepartment: "Operations",
  }),
  entry({
    id: "pub-vendor",
    domain: "public",
    category: "vendor and partnership inquiries",
    intent: "vendor_partnership",
    title: "Vendor or partnership inquiry",
    keywords: ["vendor", "supplier", "partner", "partnership", "subcontractor"],
    synonyms: {
      vendor: ["supplier", "provider"],
      partner: ["partnership", "alliance"],
    },
    exampleQuestions: [
      "I want to become a vendor",
      "Who handles partnerships?",
    ],
    responseSummary:
      "Vendor and partnership opportunities require review by the appropriate SecureMedy business contact; Medy cannot approve a relationship.",
    requiredFields: ["organization", "contact method", "capability summary"],
    suggestedReplies: ["Submit inquiry", "Speak to Operations"],
    availableActions: [
      action("contact", "start_form", "Submit Vendor Inquiry"),
    ],
    sourceLabel: publicSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Operations",
  }),
  entry({
    id: "pub-faq",
    domain: "public",
    category: "general FAQs",
    intent: "general_faq",
    title: "General public help",
    keywords: ["help", "question", "faq", "hours", "address", "phone"],
    synonyms: { help: ["support", "assistance"] },
    exampleQuestions: [
      "What can you help me with?",
      "Where is SecureMedy located?",
    ],
    responseSummary:
      "Medy can help with services, service inquiries, careers, public contact routing, complaints, and general SecureMedy information.",
    suggestedReplies: ["Explore services", "Request a quote", "Careers"],
    sourceLabel: publicSource,
    sourceStatus: "approved",
  }),
  entry({
    id: "pub-emergency",
    domain: "public",
    category: "emergency limitations",
    intent: "emergency",
    title: "Emergency guidance",
    keywords: [
      "emergency",
      "danger",
      "fire",
      "violence",
      "threat",
      "injury",
      "911",
      "weapon",
    ],
    synonyms: {
      danger: ["unsafe", "life threatening"],
      injury: ["medical emergency", "bleeding"],
    },
    exampleQuestions: [
      "There is an active threat",
      "Someone is badly injured",
      "There is a fire",
    ],
    responseSummary:
      "If anyone is in immediate danger, call 911 or local emergency services now. Move to a safe location if possible and notify the appropriate SecureMedy supervisor. Medy cannot dispatch emergency help.",
    warnings: ["Do not delay emergency action to continue this chat."],
    suggestedReplies: [],
    sourceLabel: publicSource,
    sourceStatus: "approved",
    escalationDepartment: "Operations",
    emergencyFlag: true,
  }),
];

const employeeEntries: KnowledgeEntry[] = [
  entry({
    id: "emp-payroll",
    domain: "employee",
    category: "payroll",
    intent: "payroll_issue",
    title: "Payroll issue",
    keywords: [
      "payroll",
      "paycheck",
      "hours",
      "overtime",
      "rate",
      "deduction",
      "paystub",
    ],
    synonyms: {
      paycheck: ["check", "pay"],
      paystub: ["pay slip", "earnings statement"],
      overtime: ["ot"],
    },
    exampleQuestions: [
      "My hours are missing",
      "My overtime is wrong",
      "Where is my paystub?",
      "I did not receive my paycheck",
    ],
    responseSummary:
      "Payroll issues should identify the issue type and affected pay period. Payroll must verify records and any correction; Medy does not determine wages or payment dates.",
    requiredFields: ["payroll issue type", "affected pay period"],
    optionalFields: ["shift date", "supervisor"],
    suggestedReplies: [
      "Missing hours",
      "Incorrect rate",
      "Overtime",
      "Missing paycheck",
      "Deductions",
    ],
    availableActions: [
      action(
        "payroll",
        "submit_mock_request",
        "Start Payroll Issue",
        undefined,
        true,
      ),
      action(
        "payroll-contact",
        "contact_department",
        "Contact Payroll",
        "Payroll",
      ),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Payroll",
  }),
  entry({
    id: "emp-timekeeping",
    domain: "employee",
    category: "timekeeping",
    intent: "timekeeping",
    title: "Timekeeping support",
    keywords: ["timecard", "timesheet", "clock", "punch", "hours"],
    synonyms: {
      timecard: ["timesheet", "time sheet"],
      punch: ["clock in", "clock out"],
    },
    exampleQuestions: [
      "I forgot to clock out",
      "How do I correct my timesheet?",
    ],
    responseSummary:
      "Record the affected date and shift, then contact the appropriate supervisor or Payroll channel for verification and correction.",
    requiredFields: ["affected date", "issue summary"],
    suggestedReplies: ["Yesterday", "Contact supervisor", "Contact Payroll"],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Payroll",
  }),
  entry({
    id: "emp-schedule",
    domain: "employee",
    category: "schedules",
    intent: "schedule_help",
    title: "Schedule help",
    keywords: ["schedule", "shift", "roster", "assignment", "posted"],
    synonyms: {
      schedule: ["roster", "calendar"],
      shift: ["assignment", "post"],
    },
    exampleQuestions: ["My schedule is missing", "Where can I see my shift?"],
    responseSummary:
      "Check the approved scheduling channel and contact Operations if an assigned shift is missing or unclear. Medy cannot create or change a real shift.",
    requiredFields: ["schedule issue"],
    suggestedReplies: [
      "Missing schedule",
      "Shift change",
      "Contact Operations",
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Operations",
  }),
  entry({
    id: "emp-callout",
    domain: "employee",
    category: "call-outs",
    intent: "shift_callout",
    title: "Shift call-out",
    keywords: ["call out", "callout", "absent", "cannot work", "miss shift"],
    synonyms: { "call out": ["call off", "report absence"] },
    exampleQuestions: ["I need to call out", "I cannot make my shift"],
    responseSummary:
      "Notify the designated supervisor or Operations contact as soon as possible and provide the affected shift and a safe contact method. Exact notice rules require confirmation.",
    requiredFields: ["affected shift", "supervisor notification status"],
    suggestedReplies: [
      "Today’s shift",
      "I notified my supervisor",
      "Contact Operations",
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Operations",
  }),
  entry({
    id: "emp-attendance",
    domain: "employee",
    category: "attendance",
    intent: "attendance",
    title: "Attendance or late arrival",
    keywords: ["late", "attendance", "tardy", "arrival", "absence"],
    synonyms: { late: ["running late", "tardy"] },
    exampleQuestions: ["I will be late", "I have an attendance question"],
    responseSummary:
      "Notify the appropriate supervisor or Operations contact and identify the affected shift. Medy does not state disciplinary consequences.",
    requiredFields: ["affected shift", "estimated arrival or absence"],
    suggestedReplies: [
      "Running late",
      "Unable to attend",
      "Contact supervisor",
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Operations",
  }),
  entry({
    id: "emp-leave",
    domain: "employee",
    category: "leave and PTO",
    intent: "leave_request",
    title: "Leave and PTO",
    keywords: ["leave", "pto", "vacation", "sick", "time off", "absence"],
    synonyms: {
      pto: ["paid time off", "time off"],
      vacation: ["planned leave"],
    },
    exampleQuestions: [
      "I need to request leave",
      "What is my PTO balance?",
      "I am sick today",
    ],
    responseSummary:
      "Leave questions should identify the leave type and relevant dates. HR or the approved system must confirm eligibility, balance, documentation, and approval.",
    requiredFields: ["leave type", "start date"],
    optionalFields: ["return date"],
    suggestedReplies: [
      "Planned leave",
      "Emergency absence",
      "Sick leave",
      "Check leave status",
    ],
    availableActions: [
      action("forms", "navigate", "Open Forms", PortalRoutes.forms),
      action("hr", "contact_department", "Contact HR", "Human Resources"),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Human Resources",
  }),
  entry({
    id: "emp-uniform",
    domain: "employee",
    category: "uniforms",
    intent: "uniform_request",
    title: "Uniform support",
    keywords: [
      "uniform",
      "shirt",
      "pants",
      "jacket",
      "size",
      "damaged",
      "replacement",
    ],
    synonyms: {
      pants: ["trousers"],
      damaged: ["torn", "broken"],
      size: ["fit", "too small", "too large"],
    },
    exampleQuestions: [
      "My uniform is damaged",
      "My pants are the wrong size",
      "I never received my uniform",
    ],
    responseSummary:
      "Uniform support can cover a damaged, lost, wrong-size, not-received, or new-issue item. Logistics must confirm inventory and fulfillment.",
    requiredFields: ["uniform issue type", "item"],
    optionalFields: ["size", "site"],
    suggestedReplies: [
      "Damaged item",
      "Lost item",
      "Wrong size",
      "Never received",
      "New issue",
    ],
    availableActions: [
      action(
        "uniform",
        "navigate",
        "Open Uniform Request",
        PortalRoutes.uniformRequest,
      ),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Logistics",
  }),
  entry({
    id: "emp-equipment",
    domain: "employee",
    category: "equipment",
    intent: "equipment_issue",
    title: "Equipment issue",
    keywords: [
      "equipment",
      "radio",
      "vest",
      "device",
      "badge",
      "lost",
      "damaged",
    ],
    synonyms: {
      badge: ["access card", "credential"],
      radio: ["walkie talkie"],
    },
    exampleQuestions: [
      "I lost my badge",
      "My radio is damaged",
      "I need replacement equipment",
    ],
    responseSummary:
      "Report lost or damaged equipment promptly and notify the appropriate supervisor. Medy does not assign fault or determine consequences.",
    requiredFields: ["equipment issue type", "item"],
    optionalFields: ["last known location", "incident date"],
    suggestedReplies: [
      "Lost badge",
      "Damaged radio",
      "Request replacement",
      "Contact supervisor",
    ],
    availableActions: [
      action(
        "lost-equipment",
        "submit_mock_request",
        "Report Equipment Issue",
        undefined,
        true,
      ),
      action(
        "equipment-policy",
        "navigate",
        "View Equipment Guidance",
        PortalRoutes.resources,
      ),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Operations",
  }),
  entry({
    id: "emp-license",
    domain: "employee",
    category: "licensing",
    intent: "license_status",
    title: "License and credential status",
    keywords: [
      "license",
      "licence",
      "guard card",
      "credential",
      "expired",
      "renewal",
    ],
    synonyms: {
      license: ["licence", "guard card", "credential"],
      expired: ["expiration", "renew"],
    },
    exampleQuestions: ["My license expired", "When does my guard card expire?"],
    responseSummary:
      "The demonstration profile can show a fictional credential date. HR or Compliance and the issuing authority must confirm renewal steps and official status.",
    suggestedReplies: [
      "View license details",
      "Contact Compliance",
      "Renewal guidance",
    ],
    availableActions: [
      action("license", "show_data", "View License Details"),
      action(
        "resources",
        "navigate",
        "Open Resource Library",
        PortalRoutes.resources,
      ),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "demo_only",
    disclaimers: [
      "The displayed credential record is fictional demonstration data.",
    ],
    escalationDepartment: "Compliance",
  }),
  entry({
    id: "emp-compliance",
    domain: "employee",
    category: "compliance",
    intent: "compliance",
    title: "Compliance question",
    keywords: [
      "compliance",
      "requirement",
      "certification",
      "background",
      "clearance",
    ],
    synonyms: { requirement: ["rule", "obligation"] },
    exampleQuestions: [
      "I have a compliance question",
      "Is my certification current?",
    ],
    responseSummary:
      "Compliance requirements vary by role, assignment, and jurisdiction and must be confirmed through Compliance and official sources.",
    suggestedReplies: ["Contact Compliance", "View resources"],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Compliance",
  }),
  entry({
    id: "emp-training",
    domain: "employee",
    category: "training",
    intent: "training",
    title: "Training support",
    keywords: ["training", "course", "deadline", "overdue", "certificate"],
    synonyms: { course: ["module", "class"], deadline: ["due date", "due"] },
    exampleQuestions: ["When is my training due?", "My course is overdue"],
    responseSummary:
      "The demonstration profile may show fictional assigned courses. The training system or supervisor must confirm deadlines and completion status.",
    suggestedReplies: ["View assigned training", "Contact supervisor"],
    sourceLabel: employeeSource,
    sourceStatus: "demo_only",
    disclaimers: ["Training records shown in this demo are fictional."],
    escalationDepartment: "Training",
  }),
  entry({
    id: "emp-incident",
    domain: "employee",
    category: "workplace incidents",
    intent: "incident_report",
    title: "Workplace incident",
    keywords: [
      "incident",
      "injury",
      "accident",
      "property",
      "safety",
      "vehicle",
      "damage",
    ],
    synonyms: {
      incident: ["event", "occurrence"],
      injury: ["hurt", "medical"],
    },
    exampleQuestions: [
      "I need to report an incident",
      "There was a client-site incident",
      "Property was damaged",
    ],
    responseSummary:
      "For a non-emergency incident, first ensure immediate safety, notify the appropriate supervisor, preserve relevant facts, and use the approved reporting channel. Medy does not investigate or determine liability.",
    requiredFields: ["incident type", "immediate safety status"],
    optionalFields: [
      "location",
      "date and time",
      "supervisor notification status",
    ],
    suggestedReplies: [
      "Injury",
      "Vehicle accident",
      "Client-site incident",
      "Damaged property",
      "Lost equipment",
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Operations",
  }),
  entry({
    id: "emp-injury",
    domain: "employee",
    category: "injuries",
    intent: "workplace_injury",
    title: "Workplace injury",
    keywords: ["injury", "injured", "hurt", "medical", "bleeding"],
    synonyms: { injured: ["hurt", "wounded"] },
    exampleQuestions: ["I was injured at work", "A coworker is hurt"],
    responseSummary:
      "If the injury is life-threatening or anyone is in immediate danger, call 911 or local emergency services now. Otherwise seek appropriate care, notify a supervisor, and use the approved incident process.",
    requiredFields: ["immediate danger status"],
    warnings: ["Do not delay emergency care."],
    suggestedReplies: [
      "This is an emergency",
      "No immediate danger",
      "Contact supervisor",
    ],
    sourceLabel: employeeSource,
    sourceStatus: "approved",
    escalationDepartment: "Operations",
    relatedIntents: ["emergency", "incident_report"],
  }),
  entry({
    id: "emp-hr",
    domain: "employee",
    category: "HR",
    intent: "hr_support",
    title: "Human Resources support",
    keywords: [
      "hr",
      "human resources",
      "benefits",
      "employee relations",
      "personal",
    ],
    synonyms: { hr: ["people team", "human resources"] },
    exampleQuestions: ["I need HR help", "Who handles an employment question?"],
    responseSummary:
      "Medy can route an HR question, but Human Resources must provide official guidance on benefits, eligibility, employment matters, and policy interpretation.",
    suggestedReplies: [
      "Contact HR",
      "Employment verification",
      "Leave question",
    ],
    availableActions: [
      action("hr", "contact_department", "Contact HR", "Human Resources"),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "approved",
    escalationDepartment: "Human Resources",
  }),
  entry({
    id: "emp-verification",
    domain: "employee",
    category: "employment verification",
    intent: "employment_verification",
    title: "Employment verification",
    keywords: [
      "employment verification",
      "verification",
      "proof of employment",
      "letter",
    ],
    synonyms: {
      "employment verification": ["verify employment", "proof of employment"],
    },
    exampleQuestions: [
      "I need employment verification",
      "How can a lender verify my employment?",
    ],
    responseSummary:
      "Employment verification must be handled through the approved Human Resources channel. Medy cannot generate or confirm an official employment record.",
    suggestedReplies: ["Contact HR"],
    availableActions: [
      action("hr", "contact_department", "Contact HR", "Human Resources"),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "approved",
    escalationDepartment: "Human Resources",
  }),
  entry({
    id: "emp-it",
    domain: "employee",
    category: "IT support",
    intent: "it_support",
    title: "IT support",
    keywords: ["it", "computer", "password", "login", "access", "technical"],
    synonyms: {
      password: ["credentials", "sign in"],
      login: ["log in", "sign in"],
    },
    exampleQuestions: ["I cannot log in", "I need IT support"],
    responseSummary:
      "Use the approved IT support channel for access problems. Never share your password, one-time code, or recovery answers with Medy.",
    requiredFields: ["affected system", "problem summary"],
    suggestedReplies: ["M3dyHub", "Outlook", "Teams", "Contact IT"],
    availableActions: [
      action("it", "contact_department", "Contact IT Support", "IT Support"),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "approved",
    escalationDepartment: "IT Support",
  }),
  entry({
    id: "emp-m3dyhub",
    domain: "employee",
    category: "M3dyHub access",
    intent: "m3dyhub_access",
    title: "M3dyHub access",
    keywords: ["m3dyhub", "portal", "login", "locked", "password"],
    synonyms: {
      locked: ["locked out", "cannot access"],
      login: ["sign in", "log in"],
    },
    exampleQuestions: [
      "I cannot log into M3dyHub",
      "My portal account is locked",
    ],
    responseSummary:
      "Confirm you are using the approved M3dyHub address, then contact IT if access still fails. Do not share credentials in chat.",
    requiredFields: ["access problem"],
    suggestedReplies: ["Forgot password", "Account locked", "Contact IT"],
    availableActions: [
      action("it", "contact_department", "Contact IT Support", "IT Support"),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "approved",
    escalationDepartment: "IT Support",
  }),
  entry({
    id: "emp-collaboration",
    domain: "employee",
    category: "Teams and Outlook",
    intent: "teams_outlook",
    title: "Teams or Outlook access",
    keywords: ["teams", "outlook", "email", "mailbox", "calendar"],
    synonyms: { outlook: ["email", "mailbox"], teams: ["microsoft teams"] },
    exampleQuestions: ["Outlook is not working", "I cannot access Teams"],
    responseSummary:
      "Identify the affected application and issue, then use the approved IT support channel. Do not provide passwords or security codes.",
    requiredFields: ["affected application", "problem summary"],
    suggestedReplies: ["Outlook", "Teams", "Contact IT"],
    availableActions: [
      action("it", "contact_department", "Contact IT Support", "IT Support"),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "approved",
    escalationDepartment: "IT Support",
  }),
  entry({
    id: "emp-logistics",
    domain: "employee",
    category: "logistics",
    intent: "logistics",
    title: "Logistics support",
    keywords: ["logistics", "shipment", "delivery", "supplies", "inventory"],
    synonyms: { shipment: ["delivery", "order"] },
    exampleQuestions: [
      "Where is my equipment delivery?",
      "I need logistics support",
    ],
    responseSummary:
      "Logistics can confirm demonstration requests, inventory, fulfillment, or delivery status. Medy cannot promise stock or delivery dates.",
    requiredFields: ["request or item"],
    suggestedReplies: [
      "Uniform request",
      "Equipment request",
      "Contact Logistics",
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Logistics",
  }),
  entry({
    id: "emp-fleet",
    domain: "employee",
    category: "fleet",
    intent: "fleet_issue",
    title: "Fleet and vehicle support",
    keywords: [
      "vehicle",
      "fleet",
      "car",
      "breakdown",
      "fuel card",
      "gas",
      "tire",
    ],
    synonyms: {
      breakdown: ["broke down", "disabled vehicle"],
      "fuel card": ["gas card", "fuelcard"],
    },
    exampleQuestions: ["My vehicle broke down", "My fuel card is not working"],
    responseSummary:
      "Move to a safe location if possible, notify Operations, and identify the vehicle issue. For immediate roadway danger or injury, call 911 or local emergency services.",
    requiredFields: ["fleet issue type", "immediate safety status"],
    optionalFields: ["vehicle identifier", "location"],
    suggestedReplies: [
      "Vehicle breakdown",
      "Fuel-card issue",
      "Unsafe location",
      "Contact Operations",
    ],
    sourceLabel: employeeSource,
    sourceStatus: "requires_confirmation",
    escalationDepartment: "Operations",
  }),
  entry({
    id: "emp-policy",
    domain: "employee",
    category: "policies",
    intent: "policy_question",
    title: "Policy question",
    keywords: ["policy", "procedure", "sop", "rule", "handbook"],
    synonyms: {
      policy: ["procedure", "guidance", "handbook"],
      sop: ["standard operating procedure"],
    },
    exampleQuestions: [
      "What is the attendance policy?",
      "Show me the uniform policy",
    ],
    responseSummary:
      "Medy can help locate demonstration guidance, but the current approved document and authorized department must confirm official policy requirements.",
    suggestedReplies: [
      "View policy resources",
      "Contact HR",
      "Contact Operations",
    ],
    availableActions: [
      action(
        "resources",
        "navigate",
        "Open Resource Library",
        PortalRoutes.resources,
      ),
    ],
    sourceLabel: employeeSource,
    sourceStatus: "provisional",
    disclaimers: ["DEMONSTRATION CONTENT — NOT AN OFFICIAL SECUREMEDY POLICY."],
    escalationDepartment: "Human Resources",
  }),
  entry({
    id: "emp-escalation",
    domain: "employee",
    category: "escalation contacts",
    intent: "supervisor_escalation",
    title: "Supervisor or department escalation",
    keywords: ["supervisor", "manager", "escalate", "someone", "contact"],
    synonyms: {
      supervisor: ["manager", "lead"],
      escalate: ["speak to", "talk to"],
    },
    exampleQuestions: ["I need my supervisor", "Can I escalate this?"],
    responseSummary:
      "Medy can record a demonstration handoff to the appropriate department. No real message is sent by this local demo.",
    requiredFields: ["department or issue"],
    suggestedReplies: ["Operations", "HR", "Payroll", "IT Support"],
    availableActions: [action("handoff", "escalate", "Request Escalation")],
    sourceLabel: employeeSource,
    sourceStatus: "demo_only",
    disclaimers: ["This local demo records no real external handoff."],
    escalationDepartment: "Operations",
  }),
  entry({
    id: "emp-emergency",
    domain: "employee",
    category: "emergency",
    intent: "emergency",
    title: "Employee emergency guidance",
    keywords: [
      "emergency",
      "danger",
      "fire",
      "violence",
      "active threat",
      "life threatening",
      "911",
      "weapon",
    ],
    synonyms: {
      danger: ["unsafe", "immediate threat"],
      fire: ["smoke", "flames"],
    },
    exampleQuestions: [
      "There is an active threat",
      "This is a medical emergency",
      "There is a fire",
    ],
    responseSummary:
      "If anyone is in immediate danger, call 911 or local emergency services now. Move to a safe location if possible and notify the appropriate SecureMedy supervisor. Medy cannot dispatch emergency help.",
    warnings: ["Do not delay emergency action to continue this chat."],
    sourceLabel: employeeSource,
    sourceStatus: "approved",
    escalationDepartment: "Operations",
    emergencyFlag: true,
  }),
];

export const knowledgeEntries = z
  .array(KnowledgeEntrySchema)
  .parse([...publicEntries, ...employeeEntries]);
export const knowledgeFor = (mode: Mode) =>
  knowledgeEntries.filter((item) => item.domain === mode);
